### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by flohof-UB** [ngoettin/band-calc#1]
https://github.com/ngoettin/band-calc/blob/87f76280303f8901dcd8cf2c6f4eb54e35a6051a/bandcalc/lattice/generate.py#L26

Warum wird da noch mal ein dictionary definiert. Ist in den Zeilen darüber nicht schon das gleiche dictionary mit den sortierten Vektoren erzeugt worden?

**Comment by flohof-UB** [comment]
> https://github.com/ngoettin/band-calc/blob/87f76280303f8901dcd8cf2c6f4eb54e35a6051a/bandcalc/lattice/generate.py#L25
> 
> Warum wird da noch mal ein dictionary definiert. Ist in den Zeilen darüber nicht schon das gleiche dictionary mit den sortierten Vektoren erzeugt worden?

Sorry, bin nur grad n bisschen am ausprobieren mit GitHub :D

**Comment by ngoettin** [comment]
Da werden nur alle values in numpy arrays umgewandelt. Das könnte man mit `np.append` vielleicht besser lösen, ich bin mir aber nicht ganz sicher, was schneller ist, da gerade bei solchen kleinen Operationen `numpy` etwas overhead hat
